FROM python:3.11-slim
# Set working directory
WORKDIR /usr/src/app
# copy the contents of the current local directory into the container's working directory
ADD . /usr/src/app/
# Run a command
CMD ["python", "hello.py"]